# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: dependent

on:
  push:
   branches: [test3]

jobs:
  Veracode-Result:
     
     runs-on: windows-latest
     steps:
      - name: Checkout veracode repository
        uses: actions/checkout@v2
        with:
         repository: mckesson/hvs-reporting-portal-veracode-reports

         token: ${{ secrets.API_TOKEN_GITHUB }} # `GitHub_PAT` is a secret that contains your PAT
         path: ./
  
      - name: Run the veracode file
        shell: pwsh
        run: | 
           Write-Host "Get App build list"
           
             
              
                $path= "D:\a\test-react\test-react\Veracode-file\VeracodeC#API.exe -vid ${{secrets.VERACODE_API_ID}}  -vkey ${{secrets.VERACODE_API_KEY}} -action GetBuildList  -appid 464177   -sandboxid  3331502  -outputfilepath D:\a\_temp\getbuild.xml"
               Invoke-Expression -Command "$path"
               [XML]$buildinfo = [System.Xml.XmlDocument](Get-Content  D:\a\_temp\getbuild.xml)
               $buildinfo.GetType().FullName 
              $buildnumberget= $buildinfo.buildlist.build  | Where-Object {$_.version -eq   "hvs-pharmacy-reporting-portal-ui.2021-06-24-17-08-51" } |Select-Object build_id
             $outpath="D:\a\test-react\test-react\Veracode-file\VeracodeC#API.exe -vid ${{secrets.VERACODE_API_ID}} -vkey ${{secrets.VERACODE_API_KEY}} -action DetailedReport -buildid $buildnumberget.build_id  -format pdf  -outputfilepath D:\a\_temp\hvs-pharmacy-reporting-portal-ui.2021-06-24-17-08-51.pdf"
             Invoke-Expression -Command " $outpath "
             
      
