name: React CICD
on:
 pull_request_target:
  branches: [test]
 push:
  branches: [test]
jobs:
   build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See  supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v2
       with:
        node-version: ${{ matrix.node-version }}
     - run: npm ci
     - run: CI=false npm run build
   Veracode-scan:
     needs: [build_and_test]
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v2
        - name: Veracode upload and scan
          # You may pin to the exact commit or the version.
          # uses: veracode/veracode-uploadandscan-action@c5e63c8383debb26a0d48250eab75d94327635ba
          uses: veracode/veracode-uploadandscan-action@0.2.1
          with:
           appname: RxCrossroads - Portal
           createprofile: false
           filepath: ./build
           pattern: build*
           version:  ${{ github.run_id }}
           vid: ${{ secrets.VERACODE_API_ID }}
           vkey: ${{ secrets.VERACODE_API_KEY }}
           sandboxname: Test-HVS-Portal
           selectedpreviously: True
        
