name: React CICD
on:
 pull_request_target:
  branches: [test]
 push:
  branches: [test]
jobs:
   build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See  supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v2
       with:
        node-version: ${{ matrix.node-version }}
     - run: npm ci
     - run: CI=false npm run build
     - name: Easy Zip Files
       uses: vimtor/action-zip@v1
       with:
         files: src/ 
         dest: Veracode-Archive.zip
         recursive: true
     - name: Get Time
       id: time
       uses: nanzm/get-time-action@v1.1
       with:
           timeZone: 5.5
           format: 'YYYY-MM-DD-HH-mm-ss'
     
        

   
     - id: Veracode-scan
          # You may pin to the exact commit or the version.
          # uses: veracode/veracode-uploadandscan-action@c5e63c8383debb26a0d48250eab75d94327635ba
       uses: veracode/veracode-uploadandscan-action@0.2.1
       with:
           appname: RxCrossroads - Portal
           createprofile: false
           filepath: 'Veracode-Archive.zip'
           version: ${{github.event.repository.name }}.${{ steps.time.outputs.time }}
           vid: ${{ secrets.VERACODE_API_ID }}
           vkey: ${{ secrets.VERACODE_API_KEY }}
           sandboxname: Test-HVS-Portal
           scantimeout: 120
           selectedpreviously: True
   Veracode-Result:
     needs: [build_and_test]
     runs-on: windows-latest
     steps:
      - uses: actions/checkout@v2
      - name: Run the veracode file
        shell: pwsh
        run: | 
           Write-Host "Get App build list"
           
             
               $id= "2c6823bbd50562ed3e88a2acba6e36d9"
               $ky="d352818e85caca72327b268fe670b0d246dfe3e6d1ea4a380ce19eb1bcd37e6df6056dd78c75caff064023aa060b3d9e638662cda665f1df740345f4ea750b95"
                $path= "D:\a\test-react\test-react\Veracode-Scans\VeracodeC#API.exe -vid $id  -vkey $ky -action GetBuildList  -appid 464177   -sandboxid  3331502  -outputfilepath D:\a\_temp\getbuild.xml"
               Invoke-Expression -Command "$path"
               [XML]$buildinfo = [System.Xml.XmlDocument](Get-Content  D:\a\_temp\getbuild.xml)
               $buildinfo.GetType().FullName 
              $buildnumberget= $buildinfo.buildlist.build  | Where-Object {$_.version -eq   "${{needs.build_and_test.Veracode-scan.version.outputs}}" } |Select-Object build_id
             $outpath="D:\a\test-react\test-react\Veracode-Scans\VeracodeC#API.exe -vid $id -vkey $ky -action DetailedReport -buildid $buildnumberget.build_id  -format pdf  -outputfilepath D:\a\_temp\${{needs.build_and_test.Veracode-scan.version.outputs}}.pdf"
             Invoke-Expression -Command " $outpath "
             
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Veracode-report
          path: D:\a\_temp\${{needs.build_and_test.Veracode-scan.version.outputs}}.pdf
             
          
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: Veracode-report
          uses: ./
          path: Veracode-Scans/
   
   Download-artifact:
     
     needs: [Veracode-Result]
     runs-on: ubuntu-latest
     steps:
     - name: Download a Build Artifact
       uses: actions/download-artifact@v2.0.10
       with:
          name: Veracode-report
          path: ./
     - name: Push a file to another repository
  
       uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
       env:
         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
       with:
    
         source_file: ./
    
         destination_repo:  Msrinath-71/Test
    
         destination_folder: 'Veracode-Scans'
    
         user_email: srinath.madabhushi@mckesson.com
   
         user_name: Msrinath-71
    
         destination_branch: main
    
         
    
 
     
             

