name: React CICD
on:
 pull_request_target:
  branches: [test]
 push:
  branches: [test]
jobs:
   build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See  supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v2
       with:
        node-version: ${{ matrix.node-version }}
     - run: npm ci
     - run: CI=false npm run build
     - name: Easy Zip Files
       uses: vimtor/action-zip@v1
       with:
         files: src/ 
         dest: Veracode-Archive.zip
         recursive: true
     - name: Get Time
       id: time
       uses: nanzm/get-time-action@v1.1
       with:
           timeZone: 5.5
           format: 'YYYY-MM-DD-HH-mm-ss'
     
        

   
     - id: Veracode-scan
          # You may pin to the exact commit or the version.
          # uses: veracode/veracode-uploadandscan-action@c5e63c8383debb26a0d48250eab75d94327635ba
       uses: veracode/veracode-uploadandscan-action@0.2.1
       with:
           appname: RxCrossroads - Portal
           createprofile: false
           filepath: 'Veracode-Archive.zip'
           version: ${{ steps.time.outputs.time }}
           vid: ${{ secrets.VERACODE_API_ID }}
           vkey: ${{ secrets.VERACODE_API_KEY }}
           sandboxname: Test-HVS-Portal
           scantimeout: 120
           selectedpreviously: True
   Veracode-Result:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the veracode file
        shell: pwsh
        run: | 
           Write-Host "Get App build list"
           
             
               $id= "2c6823bbd50562ed3e88a2acba6e36d9"
               $ky="d352818e85caca72327b268fe670b0d246dfe3e6d1ea4a380ce19eb1bcd37e6df6056dd78c75caff064023aa060b3d9e638662cda665f1df740345f4ea750b95"
                $path= "/home/runner/work/test-react/test-react/Veracode-Scans/VeracodeC#API.exe -vid $id  -vkey $ky -action GetBuildList  -appid 464177   -sandboxid  3331502  -outputfilepath /home/runner/work/_temp/getbuild.xml"
               Invoke-Expression -Command "$path"
               [XML]$buildinfo = [System.Xml.XmlDocument](Get-Content  /home/runner/work/_temp/getbuild.xml)
               $buildinfo.GetType().FullName 
              $buildnumberget= $buildinfo.buildlist.build  | Where-Object {$_.version -eq   "2021-06-22-19-47-54" } |Select-Object build_id
             $outpath="/home/runner/work/test-react/test-react/Veracode-Scans/VeracodeC#API.exe -vid $id -vkey $ky -action DetailedReport -buildid $buildnumberget.build_id  -format pdf  -outputfilepath /home/runner/work/_temp/2021-06-22-19-47-54.pdf"
             Invoke-Expression -Command " $outpath "
             
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Veracode-report
          path: /home/runner/work/_temp/2021-06-22-19-47-54.pdf
 
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          uses: Msrinath-71/test-react/edit/test
          name: Veracode-report
          path: ./
      - name: Copy files to another repository
        uses: nkoppel/push-files-to-another-repository@v1.0.1
        with:
    
          source-files: /home/runner/work/_temp/2021-06-22-19-47-54.pdf
    # Name of the destination username/organization
          destination-github-username: Msrinath-71
    # Destination repository
          destination-repository-name: Test
    # Email for the git commit
          user-email: srinath.madabhushi@mckesson.com
   
          destination-directory: Veracode-Scans
   
          target-branch: main
    
 
     
             

